-- COCShortKey
CREATE TABLE main.COCShortKey (
	key VARCHAR(5) NOT NULL,
	value VARCHAR(10) NOT NULL,
	CONSTRAINT COCShortKey_pk
		PRIMARY KEY (key)
);
-- Members
CREATE TABLE main.Members (
	id UNSIGNED INTEGER(11) NOT NULL,
	name VARCHAR(7) DEFAULT NULL,
	exp UNSIGNED INTEGER DEFAULT 0,
	gmt_modified UNSIGNED INTEGER(14) DEFAULT 0,
	is_baned UNSIGNED INTEGER(1) DEFAULT 0,
	gmt_create UNSIGNED INTEGER(14) DEFAULT 0 NOT NULL,
	CONSTRAINT id
		PRIMARY KEY (id)
);
-- auto-generated definition
CREATE TABLE tb_group (
	id INTEGER(11) NOT NULL
		CONSTRAINT pk_id
			PRIMARY KEY,
	exp INTEGER DEFAULT 0 NOT NULL,
	gmt_modified UNSIGNED INTEGER(14) DEFAULT 0 NOT NULL,
	gmt_create UNSIGNED INTEGER(14) DEFAULT 0 NOT NULL,
	is_baned UNSIGNED INTEGER(1) DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX uk_id
	ON tb_group (id);
-- pokeGroup
CREATE TABLE main.pokeGroup (
	id INTEGER,
	text VARCHAR(255) NOT NULL,
	CONSTRAINT pokeGroup_pk
		PRIMARY KEY (id AUTOINCREMENT)
);
CREATE UNIQUE INDEX main.pokeGroup_id_uindex
	ON main.pokeGroup (id);
