-- COCShortKey
CREATE TABLE COCShortKey
(
	key VARCHAR(5) NOT NULL
		CONSTRAINT pk_key
			PRIMARY KEY,
	value VARCHAR(10) NOT NULL
);
-- Members
CREATE TABLE Members
(
	id INTEGER(11) NOT NULL
		CONSTRAINT pk_id
			PRIMARY KEY,
	name VARCHAR(7) DEFAULT NULL,
	exp INTEGER DEFAULT 0,
	time INTEGER(14) DEFAULT 0,
	baned INTEGER(1) DEFAULT 0
);
-- pokeGroup
CREATE TABLE pokeGroup
(
	id INTEGER
		CONSTRAINT pk_id
			PRIMARY KEY AUTOINCREMENT,
	text VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX uk_id
	ON pokeGroup (id);
